[project]
name = "take-me-cloud"
version = "0.1.0"
description = "Wrapper to manage lightning ai studios"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lightning-sdk>=2026.4.23",
    "pyyaml>=6.0",
    "tqdm>=4.66.1",
]

[project.scripts]
take-me-cloud = "take_me_cloud.cli:main"
