Lightning AI:
  machine_default: "CPU"
  cloud_provider: "AWS"
  teamspace:
  
    - name: "vaishnavahari/myml"
      machine_default: "CPU"

    - name: "rwth-gut/skillcomp-ws"
      machine_default: "T4"
  
  vscode_settings_json: "take_me_cloud/vscode_settings.json"
  
